# Dr GU
- id: doi:10.1287/trsc.2024.0890
  image: images/publications/Cognitive2025.jpg
- id: doi:10.1016/j.trc.2025.105149
  image: images/publications/Comparing2025.jpg
- id: doi:10.1109/TTE.2024.3523922
  image: images/publications/Real-Time2025.jpg
- id: doi:10.1111/mice.13354
  image: images/publications/An2025.jpg
- id: doi:10.1016/j.tra.2024.104214
  image: images/publications/Feeder2024.jpg
- id: doi:10.1016/j.trb.2024.102964
  image: images/publications/Optimal_fan2024.jpg
- id: doi:10.1016/j.tre.2024.103545
  image: images/publications/Optimal_hu2024.jpg
- id: doi:10.1111/mice.13134
  image: images/publications/On2024.jpg
- id: doi:10.1016/j.ocecoaman.2023.106809
  image: images/publications/Optimal_yang2023_2.jpg
- id: doi:10.1016/j.trc.2023.104269
  image: images/publications/Efficient2023.jpg
- id: doi:10.1016/j.tra.2023.103702
  image: images/publications/Impacts2023.jpg
#- id: doi:10.16097/j.cnki.1009-6744.2023.03.027　
#  image: images/publications/Simulation2023.jpg
- id: doi:10.1016/J.TRC.2023.104054
  image: images/publications/Condition-based2023.jpg
- id: doi:10.1016/j.ocecoaman.2022.106386
  image: images/publications/Optimal_yang2023_1.jpg
- id: doi:10.1016/j.tre.2022.102656
  image: images/publications/Dynamic2022.jpg
- id: doi:10.1016/j.tre.2021.102561
  image: images/publications/Optimal_hu2022.jpg
- id: doi:10.1016/j.trc.2021.103366
  image: images/publications/Joint2021.jpg
- id: doi:10.1016/j.trb.2021.06.008
  image: images/publications/Planning2021.jpg
- id: doi:10.1016/j.trc.2021.103211
  image: images/publications/An2021.jpg
- id: doi:10.1016/j.tre.2021.102268
  image: images/publications/Atwo2021.jpg
- id: doi:10.1016/j.tre.2020.102051
  image: images/publications/Asimulation2020.jpg
- id: doi:10.1016/j.trc.2020.102623
  image: images/publications/Achieving2020.jpg
- id: doi:10.1016/j.trb.2019.11.003
  image: images/publications/Optimal2020.jpg
- id: doi:10.1016/j.trc.2019.10.006
  image: images/publications/ABayesian2019.jpg
- id: doi:10.1016/j.trb.2019.04.010
  image: images/publications/Capacity2019.jpg
- id: doi:10.1016/j.aap.2019.02.029
  image: 
- id: doi:10.1016/j.trb.2018.03.007
  image: images/publications/Optimal2018.jpg
- id: doi:10.1016/j.trb.2017.09.014
  image: images/publications/AGeneral2018.jpg
- id: doi:10.1016/j.tre.2017.08.010
  image: images/publications/Optimal2017.jpg
- id: doi:10.1016/j.trb.2016.07.010
  image: images/publications/Exploring2016.jpg
- id: doi:10.1080/21680566.2015.1052111
  image: images/publications/On2016.jpg
- id: doi:10.1016/j.trb.2015.06.012
  image: images/publications/Optimal2015.jpg
- id: doi:10.1287/trsc.2014.0537
  image: images/publications/Models2015.jpg
- id: doi:10.1016/j.tra.2015.07.001
  image: images/publications/AProblem_partI2015.jpg
- id: doi:10.1016/j.tra.2015.07.003
  image: images/publications/AProblem_partII2015.jpg
- id: doi:10.2112/SI73-109.1
  image: 
- id: doi:10.1016/j.trb.2014.06.001
  image: images/publications/On2014.jpg
- id: doi:10.1016/j.trb.2013.08.005
  image: images/publications/Maximizing2013.jpg
- id: doi:10.1016/j.trb.2012.09.005
  image: images/publications/Mitigating2013.jpg
- id: doi:10.1016/j.trb.2011.12.002
  image: images/publications/Joint2012.jpg
- id: doi:10.1016/j.trb.2012.08.006
  image: images/publications/On2012.jpg
- id: doi:10.1016/j.trb.2011.01.001
  image: images/publications/On2011.jpg

# Dr Fan
- id: doi:10.48550/arXiv.2511.21295
  image: images/publications/Fan/Fly2025.png
- id: doi:10.1016/j.tre.2025.104512
  image: images/publications/Fan/Acontinue2025.jpg
- id: doi:10.1155/atr/3607727
  image: images/publications/Fan/Onthe2025.jpg
- id: doi:10.1016/j.trc.2025.105245
  image: images/publications/Fan/Optimal2025.jpg
- id: doi:10.1016/j.trc.2025.105181
  image: images/publications/Fan/Novel2025.jpg
- id: doi:10.1016/j.trb.2024.102964
  image: images/publications/Fan/Optimal2024.jpg
- id: doi:10.1016/j.eswa.2024.124180
  image: images/publications/Fan/Optimizing2024.jpg
- id: doi:10.1016/j.trc.2024.104739
  image: images/publications/Fan/Macroscopic2024.jpg
- id: doi:10.1016/j.tre.2023.103114
  image: images/publications/Fan/Joint2023.jpg
- id: doi:10.1061/(ASCE)UP.1943-5444.0000786
  image: images/publications/Fan/Bilevel2022.jpg
- id: doi:10.1016/j.tre.2021.102600
  image: images/publications/Fan/Managing2022.jpg
- id: doi:10.1016/j.trb.2021.06.008
  image: images/publications/Fan/Planning2021_1.jpg
- id: doi:10.1109/TITS.2021.3054678
  image: images/publications/Fan/Optimal2021.png
- id: doi:10.1016/j.aap.2020.105936
  image: images/publications/Fan/Bayesian2021.jpg
- id: doi:10.1016/j.tre.2020.102119
  image: images/publications/Fan/Planning2021_2.jpg
- id: doi:10.1080/19439962.2019.1580326
  image: images/publications/Fan/Examining2019.jpg
- id: doi:10.1080/17457300.2020.1746814
  image: images/publications/Fan/Amachine2020.jpg
- id: doi:10.1109/ACCESS.2020.2996084
  image: images/publications/Fan/Schedule2020.png
- id: doi:10.1155/2020/8872748
  image: images/publications/Fan/Optimal2020_1.png
- id: doi:10.1016/j.trb.2019.11.003
  image: images/publications/Fan/Optimal2020_2.jpg
- id: doi:10.1371/journal.pone.0195927
  image: images/publications/Fan/Modeling2018.png
- id: doi:10.1016/j.trb.2018.03.007
  image: images/publications/Fan/Optimal2018.jpg
- id: doi:10.3141/2628-09
  image: images/publications/Fan/Use2017.png
- id: doi:10.1016/j.aap.2015.09.006
  image: images/publications/Fan/Safety2016.jpg
- id: doi:10.1016/j.tranpol.2016.03.001
  image: images/publications/Fan/Modeling2016.jpg
- id: doi:10.1080/15389588.2014.936012
  image: 
- id: doi:10.1061/(ASCE)UP.1943-5444.0000178
  image: images/publications/Fan/Bilevel2014.jpg
- id: doi:10.1016/j.tranpol.2013.09.002
  image: images/publications/Fan/Tradable2013.jpg
- id: doi:10.4236/jtts.2012.23028
  image: images/publications/Fan/Modeling2012.png